// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/UI/BaseIcon.vue')['default']
    BaseTooltip: typeof import('./src/components/UI/BaseTooltip.vue')['default']
    ButtonLogin: typeof import('./src/components/UI/ButtonLogin.vue')['default']
    CategoryItem: typeof import('./src/components/UI/CategoryItem.vue')['default']
    DropdownAppsListItem: typeof import('./src/components/UI/DropdownAppsListItem.vue')['default']
    DropdownSettingsAppearance: typeof import('./src/components/UI/DropdownSettingsAppearance.vue')['default']
    DropdownSettingsHeader: typeof import('./src/components/UI/DropdownSettingsHeader.vue')['default']
    DropdownSettingsLanguage: typeof import('./src/components/UI/DropdownSettingsLanguage.vue')['default']
    DropdownSettingsListItem: typeof import('./src/components/UI/DropdownSettingsListItem.vue')['default']
    DropdownSettingsLocation: typeof import('./src/components/UI/DropdownSettingsLocation.vue')['default']
    DropdownSettingsRestrictedMode: typeof import('./src/components/UI/DropdownSettingsRestrictedMode.vue')['default']
    LogoMain: typeof import('./src/components/UI/LogoMain.vue')['default']
    SearchButton: typeof import('./src/components/UI/SearchButton.vue')['default']
    SearchInput: typeof import('./src/components/UI/SearchInput.vue')['default']
    SearchResults: typeof import('./src/components/UI/SearchResults.vue')['default']
    SidebarCompactNavItem: typeof import('./src/components/UI/SidebarCompactNavItem.vue')['default']
    SidebarContent: typeof import('./src/components/SidebarContent.vue')['default']
    SidebarNavItem: typeof import('./src/components/UI/SidebarNavItem.vue')['default']
    SidebarSectionHeading: typeof import('./src/components/UI/SidebarSectionHeading.vue')['default']
    SidebarSelection: typeof import('./src/components/UI/SidebarSelection.vue')['default']
    TheCategories: typeof import('./src/components/TheCategories.vue')['default']
    TheDropdownApps: typeof import('./src/components/TheDropdownApps.vue')['default']
    TheDropdownSettings: typeof import('./src/components/TheDropdownSettings.vue')['default']
    TheDropDownSettingsMain: typeof import('./src/components/TheDropDownSettingsMain.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSearch: typeof import('./src/components/TheSearch.vue')['default']
    TheSearchMain: typeof import('./src/components/UI/TheSearchMain.vue')['default']
    TheSearchMobile: typeof import('./src/components/TheSearchMobile.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheSidebarCompact: typeof import('./src/components/TheSidebarCompact.vue')['default']
    TheSidebarMobile: typeof import('./src/components/TheSidebarMobile.vue')['default']
    TheSidebarMobileOverlay: typeof import('./src/components/TheSidebarMobileOverlay.vue')['default']
    TheVideos: typeof import('./src/components/TheVideos.vue')['default']
    VideoItem: typeof import('./src/components/UI/VideoItem.vue')['default']
    VideoItemInfo: typeof import('./src/components/UI/VideoItemInfo.vue')['default']
    VideoItemInfoDropdown: typeof import('./src/components/UI/VideoItemInfoDropdown.vue')['default']
    VideoItemListItem: typeof import('./src/components/UI/VideoItemListItem.vue')['default']
    VideoItemThumbnail: typeof import('./src/components/UI/VideoItemThumbnail.vue')['default']
    VideoItemThumbnailButton: typeof import('./src/components/UI/VideoItemThumbnailButton.vue')['default']
  }
}
